lowercaseOutputName: true
rules:
#  - pattern : 'kafka.streams<type=stream-metrics, thread.client-id=(.+)><>(.+): (.+)'
#    value: 1
#    name: kafka_streams_stream_metrics
#    labels:
#      client-id: $1
#      $2: $3
#    type: COUNTER
#  - pattern : 'kafka.streams<type=(.+), client-id=(.+), node-id=(node-[0-9]+)><>(.+):'
#    name: kafka_streams_$1_$4
#    type: GAUGE
#    labels:
#      client-id: "$2"
#      host-id: "$3"
#  - pattern : 'kafka.streams<type=(.+), client-id=(.+), topic=([-\w]+)><>(.+):'
#    name: kafka_producer_$1_$4
#    type: GAUGE
#    labels:
#      client-id: "$2"
#      topic: "$3"
  - pattern: 'kafka.streams<type=(.+), client-id=(.+)-StreamThread-(.+)><>(.+):'
    name: kafka_streams_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      thread: $3

  - pattern: 'kafka.streams<type=(.+), client-id=(.+)[^:]><>(.+):'
      name: kafka_streams_$1_$3
      type: GAUGE
      labels:
        client-id: $2

  - pattern: 'kafka.streams<type=(.+), client-id=(.+)-StreamThread-(.+)><>(.+):'
    name: kafka_streams_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      thread: $3

#  - pattern : 'kafka.streams<type=stream-metrics, client-id=([0-9a-f\-]+)><>(.+): (.+)'
#      value: 1
#      name: kafka_streams_client_metrics
#      type: GAUGE
#      labels:
#        client-id: $1
#        $2: $3
